import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

import { manorDataDir } from "./paths";

/**
 * Agent persistence model
 *
 * An AgentInfo has three identifiers; they exist for different consumers:
 *
 * - `id`        — UUID, the public stable handle. Used by IPC, by the renderer
 *                 store, and by any code that needs to refer to an agent across
 *                 status changes. Generated by `crypto.randomUUID()`. Never
 *                 mutated after creation.
 * - `agentSessionId` — the agent CLI's session UUID (Claude's `session_id`,
 *                 Codex's session id, etc.). Set once at creation from the hook
 *                 payload. Used as the *internal Map key* because the hook relay
 *                 only knows the agent session id. Never mutated.
 * - `paneId`    — the daemon's pane-keyed session id (== paneId on the renderer).
 *                 Nullable. Cleared when the agent's pane is closed or when the
 *                 relay reassigns the pane to a new agent session.
 *
 * Note: `agentSessionId` and `paneId` live in *different namespaces* and are
 * never interchangeable. Mixing them up is the bug fixed by ADR-133.
 *
 * Lookup tables:
 * - this.agents    — Map<agentSessionId, AgentInfo>  (primary store, persisted)
 * - this.idIndex  — Map<id, agentSessionId>        (in-memory only, rebuilt from agents)
 *
 * On every mutation, both maps must agree. Ticket-1 invariant tests cover this.
 */

export interface AgentInfo {
  id: string;
  agentSessionId: string;
  name: string | null;
  status: "active" | "completed" | "error" | "abandoned";
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  activatedAt: string | null;
  projectId: string | null;
  projectName: string | null;
  workspacePath: string | null;
  cwd: string;
  agentKind: "claude" | "opencode" | "codex" | "pi";
  agentCommand: string | null;
  paneId: string | null;
  lastAgentStatus: string | null;
  /** ISO timestamp set when auto-resume fires for this agent, to prevent double-launch */
  resumedAt: string | null;
}

interface PersistedState {
  agents: AgentInfo[];
}

export class AgentManager {
  private dataDir: string;
  private agents: Map<string, AgentInfo>;
  /** Secondary index: agentId → agentSessionId, kept in sync with `agents`. */
  private idIndex: Map<string, string> = new Map();
  private saveTimer: ReturnType<typeof setTimeout> | null = null;
  private retentionDays: number;
  /**
   * Number of agents pruned during construction. Surfaces to UI via
   * `getLastPruneCount()` so the renderer can show a one-time notice.
   */
  private lastPruneCount = 0;
  /**
   * Set to true by loadState when any agent was migrated from the legacy
   * claudeSessionId field. Triggers an immediate synchronous flush so the
   * rewritten file no longer contains the legacy key on disk.
   */
  private migrationPerformed = false;

  constructor(dataDir?: string, retentionDays = 90) {
    this.dataDir = dataDir ?? manorDataDir();
    this.retentionDays = retentionDays;
    this.agents = this.loadState();
    if (this.migrationPerformed) {
      // Bypass the debounce: write immediately so future loads don't re-migrate.
      this.flushNow();
    }
    this.lastPruneCount = this.pruneOlderThan(this.retentionDays);
  }

  private agentsFilePath(): string {
    return path.join(this.dataDir, "agents.json");
  }

  /**
   * Installs from before "tasks" became "agents" persisted to `tasks.json`.
   * Adopt that file once, in place, so history survives the rename.
   */
  private migrateLegacyFile(): void {
    const legacyPath = path.join(this.dataDir, "tasks.json");
    try {
      if (!fs.existsSync(this.agentsFilePath()) && fs.existsSync(legacyPath)) {
        fs.renameSync(legacyPath, this.agentsFilePath());
      }
    } catch {
      // A failed rename simply means we start from an empty store.
    }
  }

  private loadState(): Map<string, AgentInfo> {
    this.migrateLegacyFile();
    try {
      const data = fs.readFileSync(this.agentsFilePath(), "utf-8");
      const state = JSON.parse(data) as PersistedState & {
        /** Legacy top-level key from before the tasks → agents rename. */
        tasks?: AgentInfo[];
      };
      const map = new Map<string, AgentInfo>();
      const idIndex = new Map<string, string>();
      if (!state.agents && state.tasks) {
        this.migrationPerformed = true;
      }
      for (const agent of state.agents ?? state.tasks ?? []) {
        // Migrate legacy claudeSessionId → agentSessionId
        const migrated = agent as AgentInfo & { claudeSessionId?: string };
        if (!migrated.agentSessionId && migrated.claudeSessionId) {
          migrated.agentSessionId = migrated.claudeSessionId;
          delete migrated.claudeSessionId;
          this.migrationPerformed = true;
        }
        map.set(migrated.agentSessionId, migrated);
        idIndex.set(migrated.id, migrated.agentSessionId);
      }
      this.idIndex = idIndex;
      return map;
    } catch {
      return new Map();
    }
  }

  private writeStateSync(): void {
    const agents = Array.from(this.agents.values());
    const state: PersistedState = { agents };
    fs.mkdirSync(this.dataDir, { recursive: true });
    fs.writeFileSync(this.agentsFilePath(), JSON.stringify(state, null, 2));
  }

  private saveState(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
    }
    this.saveTimer = setTimeout(() => {
      this.saveTimer = null;
      this.writeStateSync();
    }, 500);
  }

  /**
   * Writes the current state to disk synchronously, cancelling any pending
   * debounced save. Used after a one-shot migration so the rewritten file is
   * on disk before the process can crash or be killed.
   */
  private flushNow(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    this.writeStateSync();
  }

  createAgent(
    data: Omit<AgentInfo, "id" | "createdAt" | "updatedAt" | "activatedAt">,
  ): AgentInfo {
    const now = new Date().toISOString();
    const agent: AgentInfo = {
      ...data,
      id: crypto.randomUUID(),
      createdAt: now,
      updatedAt: now,
      activatedAt: null,
    };
    this.agents.set(agent.agentSessionId, agent);
    this.idIndex.set(agent.id, agent.agentSessionId);
    this.saveState();
    return agent;
  }

  updateAgent(id: string, updates: Partial<AgentInfo>): AgentInfo | null {
    if ("agentSessionId" in updates) {
      throw new Error("updateAgent: agentSessionId is immutable and cannot be updated");
    }
    const agent = this.getAgentById(id);
    if (!agent) return null;
    const updated: AgentInfo = {
      ...agent,
      ...updates,
      id: agent.id,
      updatedAt: new Date().toISOString(),
    };
    this.agents.set(updated.agentSessionId, updated);
    this.saveState();
    return updated;
  }

  getAgentBySessionId(agentSessionId: string): AgentInfo | null {
    return this.agents.get(agentSessionId) ?? null;
  }

  getAgentById(id: string): AgentInfo | null {
    const sessionId = this.idIndex.get(id);
    if (!sessionId) return null;
    return this.agents.get(sessionId) ?? null;
  }

  getAllAgents(opts?: {
    projectId?: string;
    status?: string;
    limit?: number;
    offset?: number;
  }): AgentInfo[] {
    let agents = Array.from(this.agents.values());

    if (opts?.projectId !== undefined) {
      agents = agents.filter((t) => t.projectId === opts.projectId);
    }
    if (opts?.status !== undefined) {
      agents = agents.filter((t) => t.status === opts.status);
    }

    agents.sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );

    const offset = opts?.offset ?? 0;
    agents = agents.slice(offset);

    if (opts?.limit !== undefined) {
      agents = agents.slice(0, opts.limit);
    }

    return agents;
  }

  setAgentStatus(id: string, status: AgentInfo["status"]): void {
    const agent = this.getAgentById(id);
    if (!agent) return;

    const now = new Date().toISOString();
    const completedAt =
      status === "completed" || status === "error" ? now : agent.completedAt;

    const updated: AgentInfo = {
      ...agent,
      status,
      completedAt,
      updatedAt: now,
    };
    this.agents.set(updated.agentSessionId, updated);
    this.saveState();
  }

  linkPane(agentSessionId: string, paneId: string): void {
    const agent = this.agents.get(agentSessionId);
    if (!agent) return;
    const updated: AgentInfo = {
      ...agent,
      paneId,
      updatedAt: new Date().toISOString(),
    };
    this.agents.set(agentSessionId, updated);
    this.saveState();
  }

  getAgentByPaneId(paneId: string): AgentInfo | null {
    for (const agent of this.agents.values()) {
      if (agent.paneId === paneId) return agent;
    }
    return null;
  }

  getActiveAgents(): AgentInfo[] {
    return Array.from(this.agents.values()).filter((t) => t.status === "active");
  }

  deleteAgent(id: string): boolean {
    const sessionId = this.idIndex.get(id);
    if (!sessionId) return false;
    this.agents.delete(sessionId);
    this.idIndex.delete(id);
    this.saveState();
    return true;
  }

  /**
   * Removes non-active agents whose `completedAt` is older than `days` days.
   * Returns the number of agents pruned. Setting `days <= 0` disables pruning.
   */
  pruneOlderThan(days: number): number {
    if (!Number.isFinite(days) || days <= 0) return 0;
    const cutoff = Date.now() - days * 86_400_000;
    let pruned = 0;
    for (const [sessionId, agent] of this.agents) {
      if (agent.status === "active") continue;
      const completedMs = agent.completedAt ? Date.parse(agent.completedAt) : 0;
      if (completedMs && completedMs < cutoff) {
        this.agents.delete(sessionId);
        this.idIndex.delete(agent.id);
        pruned += 1;
      }
    }
    if (pruned > 0) this.saveState();
    return pruned;
  }

  /** Number of agents pruned during the last constructor call. */
  getLastPruneCount(): number {
    return this.lastPruneCount;
  }
}
