/**
 * `manor` CLI installer — writes the `manor` shell command to
 * `~/.manor/bin` on startup. Follows the same pattern as
 * `ensureHookScript()` in agent-hooks.ts.
 *
 * Two files land on disk:
 *   - manor.js  — the bundled CLI implementation (electron/manor-cli.ts),
 *                 copied from the unpacked asar so plain `node` can run it.
 *   - manor     — a bash shim that `exec`s manor.js with node, so agents
 *                 and users can just run `manor <command>`.
 *
 * Also removes the legacy `manor-webview` bash wrapper (ADR-053), which
 * this command supersedes.
 */

import * as fs from "node:fs";
import * as path from "node:path";

import { manorBinDir } from "./paths";

const MANOR_CLI_JS_PATH = path.join(manorBinDir(), "manor.js");
const MANOR_CLI_SHIM_PATH = path.join(manorBinDir(), "manor");
const LEGACY_WEBVIEW_CLI_PATH = path.join(manorBinDir(), "manor-webview");

const MANOR_CLI_SHIM = `#!/bin/bash
# manor — Manor control CLI. Generated by Manor on startup; do not edit.
exec node "$HOME/.manor/bin/manor.js" "$@"
`;

/**
 * Resolve the path to the bundled manor-cli.js source. In packaged builds
 * the asar archive isn't readable by plain Node when invoked via
 * `node /path/to/manor.js`, so we point at the unpacked copy extracted by
 * electron-builder's asarUnpack. Mirrors bundledAgentHookJsPath() in
 * agent-hooks.ts.
 */
function bundledManorCliJsPath(): string {
  return path
    .join(__dirname, "manor-cli.js")
    .replace("app.asar", "app.asar.unpacked");
}

/**
 * Ensure `~/.manor/bin/manor` (and its `manor.js` implementation) exist on
 * disk with execute permissions, and remove the legacy `manor-webview`
 * wrapper if present.
 *
 * Never throws — startup must not depend on a build artefact. If the
 * bundled JS can't be read (unit tests, dev runs from source), any
 * existing `manor.js` is left in place and a warning is logged once.
 */
export function ensureManorCli(): void {
  fs.mkdirSync(manorBinDir(), { recursive: true });

  const jsSrc = bundledManorCliJsPath();
  try {
    const jsContent = fs.readFileSync(jsSrc, "utf-8");
    fs.writeFileSync(MANOR_CLI_JS_PATH, jsContent, { mode: 0o755 });
  } catch (err) {
    console.warn(
      `[manor-cli-install] could not read bundled manor-cli.js at ${jsSrc}, leaving existing manor.js (if any) in place:`,
      err instanceof Error ? err.message : err,
    );
  }

  fs.writeFileSync(MANOR_CLI_SHIM_PATH, MANOR_CLI_SHIM, { mode: 0o755 });

  try {
    fs.rmSync(LEGACY_WEBVIEW_CLI_PATH);
  } catch {
    // Not present — nothing to clean up.
  }
}
