import fs from "node:fs";
import path from "node:path";

import { shellHistoryFile, shellZdotdir } from "./paths";

// Wrap a path in single quotes for safe embedding in a shell script. The data
// dir contains a space ("Application Support"), so the value must be quoted;
// any literal single quote is escaped as '\''.
function singleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

export class ShellManager {
  static zdotdirPath(): string {
    return shellZdotdir();
  }

  // One history file for every pane. Sharing it (plus zsh SHARE_HISTORY in the
  // generated .zshrc) means ctrl+r recalls commands across all sessions instead
  // of losing them when a window closes or you switch projects.
  static sharedHistoryFile(): string {
    return shellHistoryFile();
  }

  static setupZdotdir(): string {
    const dir = this.zdotdirPath();
    fs.mkdirSync(dir, { recursive: true });

    // Embed the shared history path directly in .zshrc rather than reading it
    // from a per-session env var. The path is a constant, and .zshrc is
    // regenerated by the (frequently-restarted) main process on every launch —
    // whereas the env var is injected by the detached terminal daemon, which
    // survives app restarts and can lag behind a code change for days. Owning
    // the path here keeps history sharing working regardless of daemon vintage.
    const histfile = singleQuote(this.sharedHistoryFile());

    const files: [string, string][] = [
      [
        ".zshenv",
        `[[ -f "\${REAL_ZDOTDIR:-$HOME}/.zshenv" ]] && source "\${REAL_ZDOTDIR:-$HOME}/.zshenv"\n`,
      ],
      [
        ".zprofile",
        `[[ -f "\${REAL_ZDOTDIR:-$HOME}/.zprofile" ]] && source "\${REAL_ZDOTDIR:-$HOME}/.zprofile"\n`,
      ],
      [
        ".zshrc",
        `[[ -f "\${REAL_ZDOTDIR:-$HOME}/.zshrc" ]] && source "\${REAL_ZDOTDIR:-$HOME}/.zshrc"
# One history file shared by every Manor pane — set after sourcing the user's
# .zshrc so it wins over whatever HISTFILE they (or the daemon) set.
HISTFILE=${histfile}
# Guarantee the shared history is deep enough to be useful without shrinking a
# user who already set a larger value in their real .zshrc (sourced above).
(( HISTSIZE < 100000 )) && HISTSIZE=100000
(( SAVEHIST < 100000 )) && SAVEHIST=100000
# Share one history across every Manor pane: append each command immediately and
# pull in commands typed in other live sessions, so ctrl+r sees them all.
setopt SHARE_HISTORY

# Emit OSC 7 (CWD reporting) on each prompt so Manor can track the working directory
__manor_osc7_precmd() {
  printf '\\e]7;file://%s%s\\e\\\\' "\${HOST}" "\${PWD}"
}
[[ -z \${precmd_functions+x} ]] && precmd_functions=()
precmd_functions+=(__manor_osc7_precmd)
`,
      ],
      [
        ".zlogin",
        `[[ -f "\${REAL_ZDOTDIR:-$HOME}/.zlogin" ]] && source "\${REAL_ZDOTDIR:-$HOME}/.zlogin"\n`,
      ],
    ];

    for (const [name, body] of files) {
      fs.writeFileSync(path.join(dir, name), body);
    }

    return dir;
  }
}
