import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

import { manorDataDir } from "./paths";

/**
 * Task persistence model
 *
 * A TaskInfo has three identifiers; they exist for different consumers:
 *
 * - `id`        — UUID, the public stable handle. Used by IPC, by the renderer
 *                 store, and by any code that needs to refer to a task across
 *                 status changes. Generated by `crypto.randomUUID()`. Never
 *                 mutated after creation.
 * - `agentSessionId` — the agent CLI's session UUID (Claude's `session_id`,
 *                 Codex's session id, etc.). Set once at creation from the hook
 *                 payload. Used as the *internal Map key* because the hook relay
 *                 only knows the agent session id. Never mutated.
 * - `paneId`    — the daemon's pane-keyed session id (== paneId on the renderer).
 *                 Nullable. Cleared when the task's pane is closed or when the
 *                 relay reassigns the pane to a new agent session.
 *
 * Note: `agentSessionId` and `paneId` live in *different namespaces* and are
 * never interchangeable. Mixing them up is the bug fixed by ADR-133.
 *
 * Lookup tables:
 * - this.tasks    — Map<agentSessionId, TaskInfo>  (primary store, persisted)
 * - this.idIndex  — Map<id, agentSessionId>        (in-memory only, rebuilt from tasks)
 *
 * On every mutation, both maps must agree. Ticket-1 invariant tests cover this.
 */

export interface TaskInfo {
  id: string;
  agentSessionId: string;
  name: string | null;
  status: "active" | "completed" | "error" | "abandoned";
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  activatedAt: string | null;
  projectId: string | null;
  projectName: string | null;
  workspacePath: string | null;
  cwd: string;
  agentKind: "claude" | "opencode" | "codex" | "pi";
  agentCommand: string | null;
  paneId: string | null;
  lastAgentStatus: string | null;
  /** ISO timestamp set when auto-resume fires for this task, to prevent double-launch */
  resumedAt: string | null;
}

interface PersistedState {
  tasks: TaskInfo[];
}

export class TaskManager {
  private dataDir: string;
  private tasks: Map<string, TaskInfo>;
  /** Secondary index: taskId → agentSessionId, kept in sync with `tasks`. */
  private idIndex: Map<string, string> = new Map();
  private saveTimer: ReturnType<typeof setTimeout> | null = null;
  private retentionDays: number;
  /**
   * Number of tasks pruned during construction. Surfaces to UI via
   * `getLastPruneCount()` so the renderer can show a one-time notice.
   */
  private lastPruneCount = 0;
  /**
   * Set to true by loadState when any task was migrated from the legacy
   * claudeSessionId field. Triggers an immediate synchronous flush so the
   * rewritten file no longer contains the legacy key on disk.
   */
  private migrationPerformed = false;

  constructor(dataDir?: string, retentionDays = 90) {
    this.dataDir = dataDir ?? manorDataDir();
    this.retentionDays = retentionDays;
    this.tasks = this.loadState();
    if (this.migrationPerformed) {
      // Bypass the debounce: write immediately so future loads don't re-migrate.
      this.flushNow();
    }
    this.lastPruneCount = this.pruneOlderThan(this.retentionDays);
  }

  private tasksFilePath(): string {
    return path.join(this.dataDir, "tasks.json");
  }

  private loadState(): Map<string, TaskInfo> {
    try {
      const data = fs.readFileSync(this.tasksFilePath(), "utf-8");
      const state: PersistedState = JSON.parse(data);
      const map = new Map<string, TaskInfo>();
      const idIndex = new Map<string, string>();
      for (const task of state.tasks ?? []) {
        // Migrate legacy claudeSessionId → agentSessionId
        const migrated = task as TaskInfo & { claudeSessionId?: string };
        if (!migrated.agentSessionId && migrated.claudeSessionId) {
          migrated.agentSessionId = migrated.claudeSessionId;
          delete migrated.claudeSessionId;
          this.migrationPerformed = true;
        }
        map.set(migrated.agentSessionId, migrated);
        idIndex.set(migrated.id, migrated.agentSessionId);
      }
      this.idIndex = idIndex;
      return map;
    } catch {
      return new Map();
    }
  }

  private writeStateSync(): void {
    const tasks = Array.from(this.tasks.values());
    const state: PersistedState = { tasks };
    fs.mkdirSync(this.dataDir, { recursive: true });
    fs.writeFileSync(this.tasksFilePath(), JSON.stringify(state, null, 2));
  }

  private saveState(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
    }
    this.saveTimer = setTimeout(() => {
      this.saveTimer = null;
      this.writeStateSync();
    }, 500);
  }

  /**
   * Writes the current state to disk synchronously, cancelling any pending
   * debounced save. Used after a one-shot migration so the rewritten file is
   * on disk before the process can crash or be killed.
   */
  private flushNow(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    this.writeStateSync();
  }

  createTask(
    data: Omit<TaskInfo, "id" | "createdAt" | "updatedAt" | "activatedAt">,
  ): TaskInfo {
    const now = new Date().toISOString();
    const task: TaskInfo = {
      ...data,
      id: crypto.randomUUID(),
      createdAt: now,
      updatedAt: now,
      activatedAt: null,
    };
    this.tasks.set(task.agentSessionId, task);
    this.idIndex.set(task.id, task.agentSessionId);
    this.saveState();
    return task;
  }

  updateTask(id: string, updates: Partial<TaskInfo>): TaskInfo | null {
    if ("agentSessionId" in updates) {
      throw new Error("updateTask: agentSessionId is immutable and cannot be updated");
    }
    const task = this.getTaskById(id);
    if (!task) return null;
    const updated: TaskInfo = {
      ...task,
      ...updates,
      id: task.id,
      updatedAt: new Date().toISOString(),
    };
    this.tasks.set(updated.agentSessionId, updated);
    this.saveState();
    return updated;
  }

  getTaskBySessionId(agentSessionId: string): TaskInfo | null {
    return this.tasks.get(agentSessionId) ?? null;
  }

  getTaskById(id: string): TaskInfo | null {
    const sessionId = this.idIndex.get(id);
    if (!sessionId) return null;
    return this.tasks.get(sessionId) ?? null;
  }

  getAllTasks(opts?: {
    projectId?: string;
    status?: string;
    limit?: number;
    offset?: number;
  }): TaskInfo[] {
    let tasks = Array.from(this.tasks.values());

    if (opts?.projectId !== undefined) {
      tasks = tasks.filter((t) => t.projectId === opts.projectId);
    }
    if (opts?.status !== undefined) {
      tasks = tasks.filter((t) => t.status === opts.status);
    }

    tasks.sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );

    const offset = opts?.offset ?? 0;
    tasks = tasks.slice(offset);

    if (opts?.limit !== undefined) {
      tasks = tasks.slice(0, opts.limit);
    }

    return tasks;
  }

  setTaskStatus(id: string, status: TaskInfo["status"]): void {
    const task = this.getTaskById(id);
    if (!task) return;

    const now = new Date().toISOString();
    const completedAt =
      status === "completed" || status === "error" ? now : task.completedAt;

    const updated: TaskInfo = {
      ...task,
      status,
      completedAt,
      updatedAt: now,
    };
    this.tasks.set(updated.agentSessionId, updated);
    this.saveState();
  }

  linkPane(agentSessionId: string, paneId: string): void {
    const task = this.tasks.get(agentSessionId);
    if (!task) return;
    const updated: TaskInfo = {
      ...task,
      paneId,
      updatedAt: new Date().toISOString(),
    };
    this.tasks.set(agentSessionId, updated);
    this.saveState();
  }

  getTaskByPaneId(paneId: string): TaskInfo | null {
    for (const task of this.tasks.values()) {
      if (task.paneId === paneId) return task;
    }
    return null;
  }

  getActiveTasks(): TaskInfo[] {
    return Array.from(this.tasks.values()).filter((t) => t.status === "active");
  }

  deleteTask(id: string): boolean {
    const sessionId = this.idIndex.get(id);
    if (!sessionId) return false;
    this.tasks.delete(sessionId);
    this.idIndex.delete(id);
    this.saveState();
    return true;
  }

  /**
   * Removes non-active tasks whose `completedAt` is older than `days` days.
   * Returns the number of tasks pruned. Setting `days <= 0` disables pruning.
   */
  pruneOlderThan(days: number): number {
    if (!Number.isFinite(days) || days <= 0) return 0;
    const cutoff = Date.now() - days * 86_400_000;
    let pruned = 0;
    for (const [sessionId, task] of this.tasks) {
      if (task.status === "active") continue;
      const completedMs = task.completedAt ? Date.parse(task.completedAt) : 0;
      if (completedMs && completedMs < cutoff) {
        this.tasks.delete(sessionId);
        this.idIndex.delete(task.id);
        pruned += 1;
      }
    }
    if (pruned > 0) this.saveState();
    return pruned;
  }

  /** Number of tasks pruned during the last constructor call. */
  getLastPruneCount(): number {
    return this.lastPruneCount;
  }
}
